//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLinhKienMayTinh.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADONMUA
    {
        public string Ma_CTHD { get; set; }
        public string MaHDM { get; set; }
        public string MaLK { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HOADON_MUAHANG HOADON_MUAHANG { get; set; }
        public virtual LINHKIEN LINHKIEN { get; set; }
    }
}
