//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLinhKienMayTinh.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIA_LK
    {
        public string MaLK { get; set; }
        public System.DateTime NgayApDung { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string NguoiThayDoi { get; set; }
    
        public virtual LINHKIEN LINHKIEN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
