//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLinhKienMayTinh.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaLinhKienUpdated
    {
        public string MaLK { get; set; }
        public decimal GiaBan { get; set; }
        public System.DateTime NgayApDung { get; set; }
    }
}
