//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLinhKienMayTinh.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINHKIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LINHKIEN()
        {
            this.CT_HOADONBAN = new HashSet<CT_HOADONBAN>();
            this.CT_HOADONMUA = new HashSet<CT_HOADONMUA>();
            this.CT_PHIEUNHAP = new HashSet<CT_PHIEUNHAP>();
            this.GIA_LK = new HashSet<GIA_LK>();
            this.GIANHAP_LK = new HashSet<GIANHAP_LK>();
        }
    
        public string MaLK { get; set; }
        public string TenLK { get; set; }
        public string LoaiLK { get; set; }
        public string NhaSX { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> NamSX { get; set; }
        public string MaNCC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADONBAN> CT_HOADONBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADONMUA> CT_HOADONMUA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIA_LK> GIA_LK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANHAP_LK> GIANHAP_LK { get; set; }
        public virtual LOAI_LK LOAI_LK { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
