//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLinhKienMayTinh.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public string MaTS { get; set; }
        public Nullable<int> BPNhapXuat { get; set; }
        public Nullable<int> BPBanHang { get; set; }
        public Nullable<int> TiLeGiaBan { get; set; }
        public Nullable<int> SLTonToiDa { get; set; }
        public Nullable<int> SLTonToiThieu { get; set; }
        public Nullable<int> SLBanToiDa { get; set; }
    
        public virtual NHOMNGUOIDUNG NHOMNGUOIDUNG { get; set; }
        public virtual NHOMNGUOIDUNG NHOMNGUOIDUNG1 { get; set; }
    }
}
